name: test
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rakudo-star:alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: zef install --force --/test App::Prove6
      - name: Run tests
        run: prove6
